version: "2"
services:
  bugzilla:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        - DB_DRIVER=${DB_DRIVER}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_PORT=${DB_PORT}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_REALNAME=${ADMIN_REALNAME}
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
